Fix crash when no post processor is defined
Exception:

> ContextErrorException: Notice: Undefined index: post_processors in /var/www/foo/vendor/liip/imagine-bundle/Liip/ImagineBundle/Imagine/Filter/FilterManager.php line 144

This happens in eZ Publish, where post processors are not (yet) supported.

Ping @crevillo